version: 2

sphinx:
  configuration: docs/source/conf.py
  python:
    version: "3.10"
  builder: sphinx

formats: ['html']

dependencies:
  - requirements: requirements.txt
  - requirements: requirements_doc.txt