version: 2
formats: all

build:
  os: ubuntu-22.04
  tools:
    python: "3.10"

python:
  install:
    - requirements: requirements.txt
    - requirements: requirements_doc.txt
    - method: pip
      path: .
      extra_requirements:
        - build
        - docs

sphinx:
  builder: html
  configuration: docs/source/conf.py
  fail_on_warning: false

documentation:
  - type: sphinx
    configuration: docs/source/conf.py
    output_dir: docs/build/html
    fail_on_warning: false
    fail_on_error: true
